from Day07.day07 import *

class TestDay7:
    def setup_method(self, method):
        input_file = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """.splitlines()
        lines = [line.strip() for line in input_file if line.strip()]
        self.test_manifold = Manifold(lines=lines)

    def test_part1(self):
        for row in self.test_manifold.updated_manifold:
            print(row)
        
        expected_output: list[str] = """
        .......|.......
        .......|.......
        ......|^|......
        ......|.|......
        .....|^|^|.....
        .....|.|.|.....
        ....|^|^|^|....
        ....|.|.|.|....
        ...|^|^|||^|...
        ...|.|.|||.|...
        ..|^|^|||^|^|..
        ..|.|.|||.|.|..
        .|^|||^||.||^|.
        .|.|||.||.||.|.
        |^|^|^|^|^|||^|
        |.|.|.|.|.|||.|
        """.splitlines()

        expected_updated_manifold = [line.strip() for line in expected_output if line.strip()]
        assert self.test_manifold.updated_manifold == expected_updated_manifold
        assert self.test_manifold.num_splits == 21

    def test_part2(self):
        paths = self.test_manifold.compute_all_possible_paths()
        for path in paths[:10]:
            print(path)
        assert self.test_manifold.num_possible_paths==40